# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven's Blog
tagline:          'Sincerely'
description:      '理性是人类灵魂中最高贵的因素'
url:              http://legato.ninja
baseurl:          http://legato.ninja/
# excerpt_separator: <!--more-->
# baseurl:           /


author:
  name:           'Steven Yifan Yang'
  url:            https://legato.ninja

paginate:         5
github: [Repository metadata]


extensions: [fenced_code_blocks]
