# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven's Blog
tagline:          '--- I know too many Stevens.'
description:      'I know too much love will kill you, but I have to love.'
url:              http://legato.ninja
baseurl:          http://legatoo.github.io/

author:
  name:           'Steven Yifan Yang'
  url:            https://legato.ninja

paginate:         5
