# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven's Blog
tagline:          '--- I know too many Stevens.'
description:      'Too Much Love Will Kill You.'
url:              http://legato.ninja
baseurl:          http://legato.ninja/
# baseurl:           /


author:
  name:           'Steven Yifan Yang'
  url:            https://legato.ninja

paginate:         5
github: [Repository metadata]


extensions: [fenced_code_blocks]
