# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven's Blog
tagline:          'A Jekyll theme'
description:      'I know too much love will kill you, but I have to love.'
url:              http://legato.ninja
baseurl:          http://legatoo.github.io/

author:
  name:           'Steven Yifan Yang'
  url:            https://legato.ninja

paginate:         5

# Custom vars
version:          2.1.0
