---
title: Steven's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
permalink: pretty
relative_permalinks: true
tagline: Sincerely
description: 种一棵树的最好时间是十年前, 其次是现在
url: http://legato.ninja
baseurl: http://legato.ninja/
author:
  name: Steven Yifan Yang
  url: https://legato.ninja
paginate: 5
github:
- Repository metadata
extensions:
- fenced_code_blocks
