# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven's Blog
tagline:          '--- I know too many Stevens.'
description:      'Too Much Love Will Kill You.'
url:              http://legato.ninja
baseurl:          http://legatoo.github.io/
# baseurl:           /


author:
  name:           'Steven Yifan Yang'
  url:            https://legato.ninja

paginate:         5
github: [Repository metadata]

gems:
  - jekyll-mentions

jekyll-mentions: https://twitter.com

excerpt_separator: ""
